### ISSUE TITLE
Make float option accessable from Benchmark::Dumb

### ISSUE THREAD

**Issue by y** [tsee/dumbbench#10]
As commented here: https://github.com/tsee/dumbbench/pull/6#issuecomment-309224466

> The option should probably also be documented under new in Dumbbench.pm along with the other constructor options.
>
> Also, can you make it accessible from the Benchmark::Dumb interface? From the docs, It looks it would need to be available as an import, like :float.

**Comment by briandfoy** [comment]
I'll be able to merge requests, but the main repo is now at briandfoy/dumbbench (and I've fixed the problem with issues and so on in that repo).
