### ISSUE TITLE
invalid reposity and bugtracker links

### ISSUE THREAD

**Issue by y** [tsee/dumbbench#8]
They point to briandfoy's deleted fork. Thus this project has no valid bugtracker if you're looking on search.cpan.org or metacpan.

**Comment by briandfoy** [comment]
Fixed in 7a3b679ee362027ba596ba5e09bb9a27baec2efb. Thanks!

**Comment by y** [comment]
The bug report link points back to your branch again, which now exists, but doesn't allow users to actually file bug reports because the issues setting was disabled and it redirects to the pull request page.

**Comment by briandfoy** [comment]
This should be fixed now. My repo is the main one and it allows issues now.
